name: library_management

on:
  push:
    branches:
      - main  # Deploy only when main branch is updated

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH }}
        
      - name: Add host key
        run: ssh-keyscan -H 13.61.5.250 >> ~/.ssh/known_hosts
        
      - name: Deploy to EC2
        run: |
          ssh ec2-user@13.61.5.250 << 'EOF'
            cd /home/ec2-user/library-management
            
            # Stop existing containers
            echo "Stopping existing containers..."
            docker compose down
            
            # Pull latest changes
            echo "Pulling latest changes..."
            git pull origin main
            
            # Rebuild and restart containers
            echo "Rebuilding and restarting containers..."
            docker compose up -d --build
            
            # Clean up old Docker images
            echo "Cleaning up old Docker images..."
            docker image prune -f
            
            echo "Deployment completed."
          EOF