name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 13.48.55.79 >> ~/.ssh/known_hosts
      
    - name: Create remote directory if it doesn't exist
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@13.48.55.79 "mkdir -p ~/app"
        
    - name: Copy docker-compose.yml to EC2
      run: |
        scp -i ~/.ssh/id_rsa docker-compose.yml ubuntu@13.48.55.79:~/app/
        
    - name: Copy application files (backend, database, frontend)
      run: |
        scp -i ~/.ssh/id_rsa -r ./backend ./frontend ./deploy.sh ubuntu@13.48.55.79:~/app/

    - name: Copy .env file separately
      run: |
        scp -i ~/.ssh/id_rsa .env ubuntu@13.48.55.79:~/app/.env

    - name: Deploy with Docker Compose
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@13.48.55.79 "cd ~/app && docker-compose pull && docker-compose up -d"

    - name: Run Deploy Script on EC2
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@13.48.55.79 "cd ~/app && chmod +x ./deploy.sh && ./deploy.sh"
