name: Deploy to EC2

on:
  push:
    branches: [ main ]  # Change to your main branch name if different
  workflow_dispatch:    # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      
    - name: Create remote directory if it doesn't exist
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "mkdir -p ~/app"
        
    - name: Copy docker-compose.yml to EC2
      run: |
        scp -i ~/.ssh/id_rsa docker-compose.yml ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/app/
        
    - name: Copy application files
      run: |
        # Add any additional files your application needs
        # For example, if you have a src directory:
        scp -i ~/.ssh/id_rsa -r ./src ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/app/
        
    - name: Deploy with Docker Compose
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd ~/app && docker-compose pull && docker-compose up -d"